// Code generated by fastssz. DO NOT EDIT.
// Hash: 52b67ea3b7cb79482579d5c3ff659d3473b41bec2511e9c0fd826505bb9f9f72
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the AttestationData object
func (a *AttestationData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AttestationData object to a target array
func (a *AttestationData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, a.Slot)

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if dst, err = a.Head.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if dst, err = a.Target.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if dst, err = a.Source.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the AttestationData object
func (a *AttestationData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 128 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	a.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if err = a.Head.UnmarshalSSZ(buf[8:48]); err != nil {
		return err
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if err = a.Target.UnmarshalSSZ(buf[48:88]); err != nil {
		return err
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if err = a.Source.UnmarshalSSZ(buf[88:128]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AttestationData object
func (a *AttestationData) SizeSSZ() (size int) {
	size = 128
	return
}

// HashTreeRoot ssz hashes the AttestationData object
func (a *AttestationData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AttestationData object with a hasher
func (a *AttestationData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(a.Slot)

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if err = a.Head.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if err = a.Target.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if err = a.Source.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AttestationData object
func (a *AttestationData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the Attestation object
func (a *Attestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the Attestation object to a target array
func (a *Attestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorID'
	dst = ssz.MarshalUint64(dst, a.ValidatorID)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Attestation object
func (a *Attestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 136 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorID'
	a.ValidatorID = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[8:136]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Attestation object
func (a *Attestation) SizeSSZ() (size int) {
	size = 136
	return
}

// HashTreeRoot ssz hashes the Attestation object
func (a *Attestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the Attestation object with a hasher
func (a *Attestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorID'
	hh.PutUint64(a.ValidatorID)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Attestation object
func (a *Attestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the SignedAttestation object
func (s *SignedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedAttestation object to a target array
func (s *SignedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorID'
	dst = ssz.MarshalUint64(dst, s.ValidatorID)

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedAttestation object
func (s *SignedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 2672 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorID'
	s.ValidatorID = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.UnmarshalSSZ(buf[8:136]); err != nil {
		return err
	}

	// Field (2) 'Signature'
	copy(s.Signature[:], buf[136:2672])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedAttestation object
func (s *SignedAttestation) SizeSSZ() (size int) {
	size = 2672
	return
}

// HashTreeRoot ssz hashes the SignedAttestation object
func (s *SignedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedAttestation object with a hasher
func (s *SignedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorID'
	hh.PutUint64(s.ValidatorID)

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedAttestation object
func (s *SignedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the AggregatedAttestation object
func (a *AggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedAttestation object to a target array
func (a *AggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (0) 'AggregationBits'
	if size := len(a.AggregationBits); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedAttestation.AggregationBits", size, 4096)
		return
	}
	dst = append(dst, a.AggregationBits...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedAttestation object
func (a *AggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.AggregationBits) == 0 {
			a.AggregationBits = make([]byte, 0, len(buf))
		}
		a.AggregationBits = append(a.AggregationBits, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedAttestation object
func (a *AggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (0) 'AggregationBits'
	size += len(a.AggregationBits)

	return
}

// HashTreeRoot ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedAttestation object with a hasher
func (a *AggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AggregationBits'
	if len(a.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.AggregationBits, 4096)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedAggregatedAttestation object to a target array
func (s *SignedAggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Proof'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Proof'
	if dst, err = s.Proof.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.UnmarshalSSZ(buf[0:128]); err != nil {
		return err
	}

	// Offset (1) 'Proof'
	if o1 = ssz.ReadOffset(buf[128:132]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Proof'
	{
		buf = tail[o1:]
		if s.Proof == nil {
			s.Proof = new(AggregatedSignatureProof)
		}
		if err = s.Proof.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (1) 'Proof'
	if s.Proof == nil {
		s.Proof = new(AggregatedSignatureProof)
	}
	size += s.Proof.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedAggregatedAttestation object with a hasher
func (s *SignedAggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Proof'
	if err = s.Proof.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedSignatureProof object to a target array
func (a *AggregatedSignatureProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'Participants'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.Participants)

	// Offset (1) 'ProofData'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Participants'
	if size := len(a.Participants); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.Participants", size, 4096)
		return
	}
	dst = append(dst, a.Participants...)

	// Field (1) 'ProofData'
	if size := len(a.ProofData); size > 1048576 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.ProofData", size, 1048576)
		return
	}
	dst = append(dst, a.ProofData...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Participants'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'ProofData'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'Participants'
	{
		buf = tail[o0:o1]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.Participants) == 0 {
			a.Participants = make([]byte, 0, len(buf))
		}
		a.Participants = append(a.Participants, buf...)
	}

	// Field (1) 'ProofData'
	{
		buf = tail[o1:]
		if len(buf) > 1048576 {
			return ssz.ErrBytesLength
		}
		if cap(a.ProofData) == 0 {
			a.ProofData = make([]byte, 0, len(buf))
		}
		a.ProofData = append(a.ProofData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'Participants'
	size += len(a.Participants)

	// Field (1) 'ProofData'
	size += len(a.ProofData)

	return
}

// HashTreeRoot ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedSignatureProof object with a hasher
func (a *AggregatedSignatureProof) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Participants'
	if len(a.Participants) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.Participants, 4096)

	// Field (1) 'ProofData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(a.ProofData))
		if byteLen > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(a.ProofData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1048576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
