// Code generated by fastssz. DO NOT EDIT.
// Hash: c54bd1c3d5920d66b8eeda25c1a65e2554897d50b1f9115abb415234952004c0
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlocksByRangeRequest object to a target array
func (b *BlocksByRangeRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'StartSlot'
	dst = ssz.MarshalUint64(dst, b.StartSlot)

	// Field (1) 'Count'
	dst = ssz.MarshalUint64(dst, b.Count)

	return
}

// UnmarshalSSZ ssz unmarshals the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 16 {
		return ssz.ErrSize
	}

	// Field (0) 'StartSlot'
	b.StartSlot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Count'
	b.Count = ssz.UnmarshallUint64(buf[8:16])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) SizeSSZ() (size int) {
	size = 16
	return
}

// HashTreeRoot ssz hashes the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlocksByRangeRequest object with a hasher
func (b *BlocksByRangeRequest) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'StartSlot'
	hh.PutUint64(b.StartSlot)

	// Field (1) 'Count'
	hh.PutUint64(b.Count)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
