// Code generated by fastssz. DO NOT EDIT.
// Hash: dual-key-devnet4
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

func (v *Validator) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

func (v *Validator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'AttestationPubkey'
	dst = append(dst, v.AttestationPubkey[:]...)

	// Field (1) 'ProposalPubkey'
	dst = append(dst, v.ProposalPubkey[:]...)

	// Field (2) 'Index'
	dst = ssz.MarshalUint64(dst, v.Index)

	return
}

func (v *Validator) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return ssz.ErrSize
	}

	// Field (0) 'AttestationPubkey'
	copy(v.AttestationPubkey[:], buf[0:52])

	// Field (1) 'ProposalPubkey'
	copy(v.ProposalPubkey[:], buf[52:104])

	// Field (2) 'Index'
	v.Index = ssz.UnmarshallUint64(buf[104:112])

	return err
}

func (v *Validator) SizeSSZ() (size int) {
	size = 112
	return
}

func (v *Validator) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

func (v *Validator) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AttestationPubkey'
	hh.PutBytes(v.AttestationPubkey[:])

	// Field (1) 'ProposalPubkey'
	hh.PutBytes(v.ProposalPubkey[:])

	// Field (2) 'Index'
	hh.PutUint64(v.Index)

	hh.Merkleize(indx)
	return
}

func (v *Validator) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
