// Code generated by fastssz. DO NOT EDIT.
// Hash: 13e17ee916722e5a044ab4ad4cb964b606dda40bcb9ce66b227a3d82f050aeb5
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the AggregatedAttestation object
func (a *AggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedAttestation object to a target array
func (a *AggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.AggregationBits)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (0) 'AggregationBits'
	if size := len(a.AggregationBits); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedAttestation.AggregationBits", size, 4096)
		return
	}
	dst = append(dst, a.AggregationBits...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedAttestation object
func (a *AggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.AggregationBits) == 0 {
			a.AggregationBits = make([]byte, 0, len(buf))
		}
		a.AggregationBits = append(a.AggregationBits, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedAttestation object
func (a *AggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (0) 'AggregationBits'
	size += len(a.AggregationBits)

	return
}

// HashTreeRoot ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedAttestation object with a hasher
func (a *AggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AggregationBits'
	if len(a.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.AggregationBits, 4096)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedSignatureProof object to a target array
func (a *AggregatedSignatureProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'Participants'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.Participants)

	// Offset (1) 'ProofData'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.ProofData)

	// Field (0) 'Participants'
	if size := len(a.Participants); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.Participants", size, 4096)
		return
	}
	dst = append(dst, a.Participants...)

	// Field (1) 'ProofData'
	if size := len(a.ProofData); size > 1048576 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.ProofData", size, 1048576)
		return
	}
	dst = append(dst, a.ProofData...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Participants'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'ProofData'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'Participants'
	{
		buf = tail[o0:o1]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.Participants) == 0 {
			a.Participants = make([]byte, 0, len(buf))
		}
		a.Participants = append(a.Participants, buf...)
	}

	// Field (1) 'ProofData'
	{
		buf = tail[o1:]
		if len(buf) > 1048576 {
			return ssz.ErrBytesLength
		}
		if cap(a.ProofData) == 0 {
			a.ProofData = make([]byte, 0, len(buf))
		}
		a.ProofData = append(a.ProofData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'Participants'
	size += len(a.Participants)

	// Field (1) 'ProofData'
	size += len(a.ProofData)

	return
}

// HashTreeRoot ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedSignatureProof object with a hasher
func (a *AggregatedSignatureProof) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Participants'
	if len(a.Participants) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.Participants, 4096)

	// Field (1) 'ProofData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(a.ProofData))
		if byteLen > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(a.ProofData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1048576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
