// Code generated by fastssz. DO NOT EDIT.
// Hash: 9fc6c6dea2131d3bc00342888a83608cd58920d9ea16a8cf71ab5dc1d452cd51
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Config object
func (c *Config) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the Config object to a target array
func (c *Config) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'NumValidators'
	dst = ssz.MarshalUint64(dst, c.NumValidators)

	// Field (1) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, c.GenesisTime)

	return
}

// UnmarshalSSZ ssz unmarshals the Config object
func (c *Config) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 16 {
		return ssz.ErrSize
	}

	// Field (0) 'NumValidators'
	c.NumValidators = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'GenesisTime'
	c.GenesisTime = ssz.UnmarshallUint64(buf[8:16])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Config object
func (c *Config) SizeSSZ() (size int) {
	size = 16
	return
}

// HashTreeRoot ssz hashes the Config object
func (c *Config) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the Config object with a hasher
func (c *Config) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'NumValidators'
	hh.PutUint64(c.NumValidators)

	// Field (1) 'GenesisTime'
	hh.PutUint64(c.GenesisTime)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Config object
func (c *Config) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}
