// Code generated by fastssz. DO NOT EDIT.
// Hash: b60ca7a3fc63a099494c4e77b86c5327b9f84725eff50f9f1c817f521f630326
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the AttestationData object
func (a *AttestationData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AttestationData object to a target array
func (a *AttestationData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, a.Slot)

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if dst, err = a.Head.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if dst, err = a.Target.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if dst, err = a.Source.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the AttestationData object
func (a *AttestationData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 128 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	a.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if err = a.Head.UnmarshalSSZ(buf[8:48]); err != nil {
		return err
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if err = a.Target.UnmarshalSSZ(buf[48:88]); err != nil {
		return err
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if err = a.Source.UnmarshalSSZ(buf[88:128]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AttestationData object
func (a *AttestationData) SizeSSZ() (size int) {
	size = 128
	return
}

// HashTreeRoot ssz hashes the AttestationData object
func (a *AttestationData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AttestationData object with a hasher
func (a *AttestationData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(a.Slot)

	// Field (1) 'Head'
	if a.Head == nil {
		a.Head = new(Checkpoint)
	}
	if err = a.Head.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if err = a.Target.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if err = a.Source.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AttestationData object
func (a *AttestationData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the Attestation object
func (a *Attestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the Attestation object to a target array
func (a *Attestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorID'
	dst = ssz.MarshalUint64(dst, a.ValidatorID)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Attestation object
func (a *Attestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 136 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorID'
	a.ValidatorID = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[8:136]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Attestation object
func (a *Attestation) SizeSSZ() (size int) {
	size = 136
	return
}

// HashTreeRoot ssz hashes the Attestation object
func (a *Attestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the Attestation object with a hasher
func (a *Attestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorID'
	hh.PutUint64(a.ValidatorID)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Attestation object
func (a *Attestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the SignedAttestation object
func (s *SignedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedAttestation object to a target array
func (s *SignedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorID'
	dst = ssz.MarshalUint64(dst, s.ValidatorID)

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedAttestation object
func (s *SignedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 2672 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorID'
	s.ValidatorID = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.UnmarshalSSZ(buf[8:136]); err != nil {
		return err
	}

	// Field (2) 'Signature'
	copy(s.Signature[:], buf[136:2672])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedAttestation object
func (s *SignedAttestation) SizeSSZ() (size int) {
	size = 2672
	return
}

// HashTreeRoot ssz hashes the SignedAttestation object
func (s *SignedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedAttestation object with a hasher
func (s *SignedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorID'
	hh.PutUint64(s.ValidatorID)

	// Field (1) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedAttestation object
func (s *SignedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the AggregatedAttestation object
func (a *AggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedAttestation object to a target array
func (a *AggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (0) 'AggregationBits'
	if size := len(a.AggregationBits); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedAttestation.AggregationBits", size, 4096)
		return
	}
	dst = append(dst, a.AggregationBits...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedAttestation object
func (a *AggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.AggregationBits) == 0 {
			a.AggregationBits = make([]byte, 0, len(buf))
		}
		a.AggregationBits = append(a.AggregationBits, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedAttestation object
func (a *AggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (0) 'AggregationBits'
	size += len(a.AggregationBits)

	return
}

// HashTreeRoot ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedAttestation object with a hasher
func (a *AggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AggregationBits'
	if len(a.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.AggregationBits, 4096)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedAttestation object
func (a *AggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedAggregatedAttestation object to a target array
func (s *SignedAggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Proof'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Proof'
	if dst, err = s.Proof.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.UnmarshalSSZ(buf[0:128]); err != nil {
		return err
	}

	// Offset (1) 'Proof'
	if o1 = ssz.ReadOffset(buf[128:132]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Proof'
	{
		buf = tail[o1:]
		if s.Proof == nil {
			s.Proof = new(AggregatedSignatureProof)
		}
		if err = s.Proof.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (1) 'Proof'
	if s.Proof == nil {
		s.Proof = new(AggregatedSignatureProof)
	}
	size += s.Proof.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedAggregatedAttestation object with a hasher
func (s *SignedAggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Proof'
	if err = s.Proof.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the BlockHeader object
func (b *BlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlockHeader object to a target array
func (b *BlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, b.ProposerIndex)

	// Field (2) 'ParentRoot'
	dst = append(dst, b.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, b.StateRoot[:]...)

	// Field (4) 'BodyRoot'
	dst = append(dst, b.BodyRoot[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BlockHeader object
func (b *BlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ProposerIndex'
	b.ProposerIndex = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'ParentRoot'
	copy(b.ParentRoot[:], buf[16:48])

	// Field (3) 'StateRoot'
	copy(b.StateRoot[:], buf[48:80])

	// Field (4) 'BodyRoot'
	copy(b.BodyRoot[:], buf[80:112])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlockHeader object
func (b *BlockHeader) SizeSSZ() (size int) {
	size = 112
	return
}

// HashTreeRoot ssz hashes the BlockHeader object
func (b *BlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlockHeader object with a hasher
func (b *BlockHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(b.Slot)

	// Field (1) 'ProposerIndex'
	hh.PutUint64(b.ProposerIndex)

	// Field (2) 'ParentRoot'
	hh.PutBytes(b.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(b.StateRoot[:])

	// Field (4) 'BodyRoot'
	hh.PutBytes(b.BodyRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlockHeader object
func (b *BlockHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the BlockBody object
func (b *BlockBody) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlockBody object to a target array
func (b *BlockBody) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Attestations'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Attestations'
	if size := len(b.Attestations); size > 4096 {
		err = ssz.ErrListTooBigFn("BlockBody.Attestations", size, 4096)
		return
	}
	{
		offset = 4 * len(b.Attestations)
		for ii := 0; ii < len(b.Attestations); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Attestations[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Attestations); ii++ {
		if dst, err = b.Attestations[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlockBody object
func (b *BlockBody) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Attestations'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Attestations'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 4096)
		if err != nil {
			return err
		}
		b.Attestations = make([]*AggregatedAttestation, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Attestations[indx] == nil {
				b.Attestations[indx] = new(AggregatedAttestation)
			}
			if err = b.Attestations[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlockBody object
func (b *BlockBody) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Attestations'
	for ii := 0; ii < len(b.Attestations); ii++ {
		size += 4
		size += b.Attestations[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the BlockBody object
func (b *BlockBody) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlockBody object with a hasher
func (b *BlockBody) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Attestations'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Attestations))
		if num > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Attestations {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4096)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlockBody object
func (b *BlockBody) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the Block object
func (b *Block) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the Block object to a target array
func (b *Block) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(84)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, b.ProposerIndex)

	// Field (2) 'ParentRoot'
	dst = append(dst, b.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, b.StateRoot[:]...)

	// Offset (4) 'Body'
	dst = ssz.WriteOffset(dst, offset)

	// Field (4) 'Body'
	if dst, err = b.Body.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Block object
func (b *Block) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 84 {
		return ssz.ErrSize
	}

	tail := buf
	var o4 uint64

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ProposerIndex'
	b.ProposerIndex = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'ParentRoot'
	copy(b.ParentRoot[:], buf[16:48])

	// Field (3) 'StateRoot'
	copy(b.StateRoot[:], buf[48:80])

	// Offset (4) 'Body'
	if o4 = ssz.ReadOffset(buf[80:84]); o4 > size {
		return ssz.ErrOffset
	}

	if o4 != 84 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (4) 'Body'
	{
		buf = tail[o4:]
		if b.Body == nil {
			b.Body = new(BlockBody)
		}
		if err = b.Body.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Block object
func (b *Block) SizeSSZ() (size int) {
	size = 84

	// Field (4) 'Body'
	if b.Body == nil {
		b.Body = new(BlockBody)
	}
	size += b.Body.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the Block object
func (b *Block) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the Block object with a hasher
func (b *Block) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(b.Slot)

	// Field (1) 'ProposerIndex'
	hh.PutUint64(b.ProposerIndex)

	// Field (2) 'ParentRoot'
	hh.PutBytes(b.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(b.StateRoot[:])

	// Field (4) 'Body'
	if err = b.Body.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Block object
func (b *Block) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatedSignatureProof object to a target array
func (a *AggregatedSignatureProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'Participants'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.Participants)

	// Offset (1) 'ProofData'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Participants'
	if size := len(a.Participants); size > 4096 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.Participants", size, 4096)
		return
	}
	dst = append(dst, a.Participants...)

	// Field (1) 'ProofData'
	if size := len(a.ProofData); size > 1048576 {
		err = ssz.ErrBytesLengthFn("AggregatedSignatureProof.ProofData", size, 1048576)
		return
	}
	dst = append(dst, a.ProofData...)

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Participants'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'ProofData'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'Participants'
	{
		buf = tail[o0:o1]
		if err = ssz.ValidateBitlist(buf, 4096); err != nil {
			return err
		}
		if cap(a.Participants) == 0 {
			a.Participants = make([]byte, 0, len(buf))
		}
		a.Participants = append(a.Participants, buf...)
	}

	// Field (1) 'ProofData'
	{
		buf = tail[o1:]
		if len(buf) > 1048576 {
			return ssz.ErrBytesLength
		}
		if cap(a.ProofData) == 0 {
			a.ProofData = make([]byte, 0, len(buf))
		}
		a.ProofData = append(a.ProofData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'Participants'
	size += len(a.Participants)

	// Field (1) 'ProofData'
	size += len(a.ProofData)

	return
}

// HashTreeRoot ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatedSignatureProof object with a hasher
func (a *AggregatedSignatureProof) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Participants'
	if len(a.Participants) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.Participants, 4096)

	// Field (1) 'ProofData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(a.ProofData))
		if byteLen > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(a.ProofData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1048576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatedSignatureProof object
func (a *AggregatedSignatureProof) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the BlockSignatures object
func (b *BlockSignatures) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlockSignatures object to a target array
func (b *BlockSignatures) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(2540)

	// Offset (0) 'AttestationSignatures'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'ProposerSignature'
	dst = append(dst, b.ProposerSignature[:]...)

	// Field (0) 'AttestationSignatures'
	if size := len(b.AttestationSignatures); size > 4096 {
		err = ssz.ErrListTooBigFn("BlockSignatures.AttestationSignatures", size, 4096)
		return
	}
	{
		offset = 4 * len(b.AttestationSignatures)
		for ii := 0; ii < len(b.AttestationSignatures); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.AttestationSignatures[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.AttestationSignatures); ii++ {
		if dst, err = b.AttestationSignatures[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlockSignatures object
func (b *BlockSignatures) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 2540 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AttestationSignatures'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 2540 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'ProposerSignature'
	copy(b.ProposerSignature[:], buf[4:2540])

	// Field (0) 'AttestationSignatures'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 4096)
		if err != nil {
			return err
		}
		b.AttestationSignatures = make([]*AggregatedSignatureProof, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.AttestationSignatures[indx] == nil {
				b.AttestationSignatures[indx] = new(AggregatedSignatureProof)
			}
			if err = b.AttestationSignatures[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlockSignatures object
func (b *BlockSignatures) SizeSSZ() (size int) {
	size = 2540

	// Field (0) 'AttestationSignatures'
	for ii := 0; ii < len(b.AttestationSignatures); ii++ {
		size += 4
		size += b.AttestationSignatures[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the BlockSignatures object
func (b *BlockSignatures) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlockSignatures object with a hasher
func (b *BlockSignatures) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AttestationSignatures'
	{
		subIndx := hh.Index()
		num := uint64(len(b.AttestationSignatures))
		if num > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.AttestationSignatures {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4096)
	}

	// Field (1) 'ProposerSignature'
	hh.PutBytes(b.ProposerSignature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlockSignatures object
func (b *BlockSignatures) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the SignedBlock object
func (s *SignedBlock) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedBlock object to a target array
func (s *SignedBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'Block'
	dst = ssz.WriteOffset(dst, offset)
	if s.Block == nil {
		s.Block = new(Block)
	}
	offset += s.Block.SizeSSZ()

	// Offset (1) 'Signature'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Block'
	if dst, err = s.Block.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	if dst, err = s.Signature.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedBlock object
func (s *SignedBlock) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Block'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Signature'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'Block'
	{
		buf = tail[o0:o1]
		if s.Block == nil {
			s.Block = new(Block)
		}
		if err = s.Block.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (1) 'Signature'
	{
		buf = tail[o1:]
		if s.Signature == nil {
			s.Signature = new(BlockSignatures)
		}
		if err = s.Signature.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedBlock object
func (s *SignedBlock) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'Block'
	if s.Block == nil {
		s.Block = new(Block)
	}
	size += s.Block.SizeSSZ()

	// Field (1) 'Signature'
	if s.Signature == nil {
		s.Signature = new(BlockSignatures)
	}
	size += s.Signature.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedBlock object
func (s *SignedBlock) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedBlock object with a hasher
func (s *SignedBlock) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Block'
	if err = s.Block.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	if err = s.Signature.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedBlock object
func (s *SignedBlock) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlocksByRangeRequest object to a target array
func (b *BlocksByRangeRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'StartSlot'
	dst = ssz.MarshalUint64(dst, b.StartSlot)

	// Field (1) 'Count'
	dst = ssz.MarshalUint64(dst, b.Count)

	return
}

// UnmarshalSSZ ssz unmarshals the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 16 {
		return ssz.ErrSize
	}

	// Field (0) 'StartSlot'
	b.StartSlot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Count'
	b.Count = ssz.UnmarshallUint64(buf[8:16])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) SizeSSZ() (size int) {
	size = 16
	return
}

// HashTreeRoot ssz hashes the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlocksByRangeRequest object with a hasher
func (b *BlocksByRangeRequest) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'StartSlot'
	hh.PutUint64(b.StartSlot)

	// Field (1) 'Count'
	hh.PutUint64(b.Count)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BlocksByRangeRequest object
func (b *BlocksByRangeRequest) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the Checkpoint object
func (c *Checkpoint) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the Checkpoint object to a target array
func (c *Checkpoint) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Root'
	dst = append(dst, c.Root[:]...)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, c.Slot)

	return
}

// UnmarshalSSZ ssz unmarshals the Checkpoint object
func (c *Checkpoint) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 40 {
		return ssz.ErrSize
	}

	// Field (0) 'Root'
	copy(c.Root[:], buf[0:32])

	// Field (1) 'Slot'
	c.Slot = ssz.UnmarshallUint64(buf[32:40])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Checkpoint object
func (c *Checkpoint) SizeSSZ() (size int) {
	size = 40
	return
}

// HashTreeRoot ssz hashes the Checkpoint object
func (c *Checkpoint) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the Checkpoint object with a hasher
func (c *Checkpoint) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Root'
	hh.PutBytes(c.Root[:])

	// Field (1) 'Slot'
	hh.PutUint64(c.Slot)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Checkpoint object
func (c *Checkpoint) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}

// MarshalSSZ ssz marshals the ChainConfig object
func (c *ChainConfig) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the ChainConfig object to a target array
func (c *ChainConfig) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, c.GenesisTime)

	return
}

// UnmarshalSSZ ssz unmarshals the ChainConfig object
func (c *ChainConfig) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return ssz.ErrSize
	}

	// Field (0) 'GenesisTime'
	c.GenesisTime = ssz.UnmarshallUint64(buf[0:8])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ChainConfig object
func (c *ChainConfig) SizeSSZ() (size int) {
	size = 8
	return
}

// HashTreeRoot ssz hashes the ChainConfig object
func (c *ChainConfig) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the ChainConfig object with a hasher
func (c *ChainConfig) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'GenesisTime'
	hh.PutUint64(c.GenesisTime)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ChainConfig object
func (c *ChainConfig) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}

// MarshalSSZ ssz marshals the State object
func (s *State) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the State object to a target array
func (s *State) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(228)

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(ChainConfig)
	}
	if dst, err = s.Config.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if dst, err = s.LatestBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if dst, err = s.LatestJustified.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if dst, err = s.LatestFinalized.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (5) 'HistoricalBlockHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.HistoricalBlockHashes) * 32

	// Offset (6) 'JustifiedSlots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustifiedSlots)

	// Offset (7) 'Validators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.Validators) * 112

	// Offset (8) 'JustificationsRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustificationsRoots) * 32

	// Offset (9) 'JustificationsValidators'
	dst = ssz.WriteOffset(dst, offset)

	// Field (5) 'HistoricalBlockHashes'
	if size := len(s.HistoricalBlockHashes); size > 262144 {
		err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
		return
	}
	for ii := 0; ii < len(s.HistoricalBlockHashes); ii++ {
		if size := len(s.HistoricalBlockHashes[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("State.HistoricalBlockHashes[ii]", size, 32)
			return
		}
		dst = append(dst, s.HistoricalBlockHashes[ii]...)
	}

	// Field (6) 'JustifiedSlots'
	if size := len(s.JustifiedSlots); size > 262144 {
		err = ssz.ErrBytesLengthFn("State.JustifiedSlots", size, 262144)
		return
	}
	dst = append(dst, s.JustifiedSlots...)

	// Field (7) 'Validators'
	if size := len(s.Validators); size > 4096 {
		err = ssz.ErrListTooBigFn("State.Validators", size, 4096)
		return
	}
	for ii := 0; ii < len(s.Validators); ii++ {
		if dst, err = s.Validators[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (8) 'JustificationsRoots'
	if size := len(s.JustificationsRoots); size > 262144 {
		err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
		return
	}
	for ii := 0; ii < len(s.JustificationsRoots); ii++ {
		if size := len(s.JustificationsRoots[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("State.JustificationsRoots[ii]", size, 32)
			return
		}
		dst = append(dst, s.JustificationsRoots[ii]...)
	}

	// Field (9) 'JustificationsValidators'
	if size := len(s.JustificationsValidators); size > 1073741824 {
		err = ssz.ErrBytesLengthFn("State.JustificationsValidators", size, 1073741824)
		return
	}
	dst = append(dst, s.JustificationsValidators...)

	return
}

// UnmarshalSSZ ssz unmarshals the State object
func (s *State) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 228 {
		return ssz.ErrSize
	}

	tail := buf
	var o5, o6, o7, o8, o9 uint64

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(ChainConfig)
	}
	if err = s.Config.UnmarshalSSZ(buf[0:8]); err != nil {
		return err
	}

	// Field (1) 'Slot'
	s.Slot = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.UnmarshalSSZ(buf[16:128]); err != nil {
		return err
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.UnmarshalSSZ(buf[128:168]); err != nil {
		return err
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.UnmarshalSSZ(buf[168:208]); err != nil {
		return err
	}

	// Offset (5) 'HistoricalBlockHashes'
	if o5 = ssz.ReadOffset(buf[208:212]); o5 > size {
		return ssz.ErrOffset
	}

	if o5 != 228 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (6) 'JustifiedSlots'
	if o6 = ssz.ReadOffset(buf[212:216]); o6 > size || o5 > o6 {
		return ssz.ErrOffset
	}

	// Offset (7) 'Validators'
	if o7 = ssz.ReadOffset(buf[216:220]); o7 > size || o6 > o7 {
		return ssz.ErrOffset
	}

	// Offset (8) 'JustificationsRoots'
	if o8 = ssz.ReadOffset(buf[220:224]); o8 > size || o7 > o8 {
		return ssz.ErrOffset
	}

	// Offset (9) 'JustificationsValidators'
	if o9 = ssz.ReadOffset(buf[224:228]); o9 > size || o8 > o9 {
		return ssz.ErrOffset
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		buf = tail[o5:o6]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.HistoricalBlockHashes = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(s.HistoricalBlockHashes[ii]) == 0 {
				s.HistoricalBlockHashes[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			s.HistoricalBlockHashes[ii] = append(s.HistoricalBlockHashes[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (6) 'JustifiedSlots'
	{
		buf = tail[o6:o7]
		if err = ssz.ValidateBitlist(buf, 262144); err != nil {
			return err
		}
		if cap(s.JustifiedSlots) == 0 {
			s.JustifiedSlots = make([]byte, 0, len(buf))
		}
		s.JustifiedSlots = append(s.JustifiedSlots, buf...)
	}

	// Field (7) 'Validators'
	{
		buf = tail[o7:o8]
		num, err := ssz.DivideInt2(len(buf), 112, 4096)
		if err != nil {
			return err
		}
		s.Validators = make([]*Validator, num)
		for ii := 0; ii < num; ii++ {
			if s.Validators[ii] == nil {
				s.Validators[ii] = new(Validator)
			}
			if err = s.Validators[ii].UnmarshalSSZ(buf[ii*112 : (ii+1)*112]); err != nil {
				return err
			}
		}
	}

	// Field (8) 'JustificationsRoots'
	{
		buf = tail[o8:o9]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.JustificationsRoots = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(s.JustificationsRoots[ii]) == 0 {
				s.JustificationsRoots[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			s.JustificationsRoots[ii] = append(s.JustificationsRoots[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (9) 'JustificationsValidators'
	{
		buf = tail[o9:]
		if err = ssz.ValidateBitlist(buf, 1073741824); err != nil {
			return err
		}
		if cap(s.JustificationsValidators) == 0 {
			s.JustificationsValidators = make([]byte, 0, len(buf))
		}
		s.JustificationsValidators = append(s.JustificationsValidators, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the State object
func (s *State) SizeSSZ() (size int) {
	size = 228

	// Field (5) 'HistoricalBlockHashes'
	size += len(s.HistoricalBlockHashes) * 32

	// Field (6) 'JustifiedSlots'
	size += len(s.JustifiedSlots)

	// Field (7) 'Validators'
	size += len(s.Validators) * 112

	// Field (8) 'JustificationsRoots'
	size += len(s.JustificationsRoots) * 32

	// Field (9) 'JustificationsValidators'
	size += len(s.JustificationsValidators)

	return
}

// HashTreeRoot ssz hashes the State object
func (s *State) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the State object with a hasher
func (s *State) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(ChainConfig)
	}
	if err = s.Config.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Slot'
	hh.PutUint64(s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		if size := len(s.HistoricalBlockHashes); size > 262144 {
			err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.HistoricalBlockHashes {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}
		numItems := uint64(len(s.HistoricalBlockHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (6) 'JustifiedSlots'
	if len(s.JustifiedSlots) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustifiedSlots, 262144)

	// Field (7) 'Validators'
	{
		subIndx := hh.Index()
		num := uint64(len(s.Validators))
		if num > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range s.Validators {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4096)
	}

	// Field (8) 'JustificationsRoots'
	{
		if size := len(s.JustificationsRoots); size > 262144 {
			err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.JustificationsRoots {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}
		numItems := uint64(len(s.JustificationsRoots))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (9) 'JustificationsValidators'
	if len(s.JustificationsValidators) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustificationsValidators, 1073741824)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the State object
func (s *State) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}

// MarshalSSZ ssz marshals the Validator object
func (v *Validator) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the Validator object to a target array
func (v *Validator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'AttestationPubkey'
	dst = append(dst, v.AttestationPubkey[:]...)

	// Field (1) 'ProposalPubkey'
	dst = append(dst, v.ProposalPubkey[:]...)

	// Field (2) 'Index'
	dst = ssz.MarshalUint64(dst, v.Index)

	return
}

// UnmarshalSSZ ssz unmarshals the Validator object
func (v *Validator) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return ssz.ErrSize
	}

	// Field (0) 'AttestationPubkey'
	copy(v.AttestationPubkey[:], buf[0:52])

	// Field (1) 'ProposalPubkey'
	copy(v.ProposalPubkey[:], buf[52:104])

	// Field (2) 'Index'
	v.Index = ssz.UnmarshallUint64(buf[104:112])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Validator object
func (v *Validator) SizeSSZ() (size int) {
	size = 112
	return
}

// HashTreeRoot ssz hashes the Validator object
func (v *Validator) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the Validator object with a hasher
func (v *Validator) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AttestationPubkey'
	hh.PutBytes(v.AttestationPubkey[:])

	// Field (1) 'ProposalPubkey'
	hh.PutBytes(v.ProposalPubkey[:])

	// Field (2) 'Index'
	hh.PutUint64(v.Index)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Validator object
func (v *Validator) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
