// Code generated by fastssz. DO NOT EDIT.
// Hash: aeb5298883701763283ca3a5630096026f28750d62f9609c9bb75b7f9f6d9b98
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedAggregatedAttestation object to a target array
func (s *SignedAggregatedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(132)

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Proof'
	dst = ssz.WriteOffset(dst, offset)
	if s.Proof == nil {
		s.Proof = new(AggregatedSignatureProof)
	}
	offset += s.Proof.SizeSSZ()

	// Field (1) 'Proof'
	if dst, err = s.Proof.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 132 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.UnmarshalSSZ(buf[0:128]); err != nil {
		return err
	}

	// Offset (1) 'Proof'
	if o1 = ssz.ReadOffset(buf[128:132]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 < 132 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Proof'
	{
		buf = tail[o1:]
		if s.Proof == nil {
			s.Proof = new(AggregatedSignatureProof)
		}
		if err = s.Proof.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) SizeSSZ() (size int) {
	size = 132

	// Field (1) 'Proof'
	if s.Proof == nil {
		s.Proof = new(AggregatedSignatureProof)
	}
	size += s.Proof.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedAggregatedAttestation object with a hasher
func (s *SignedAggregatedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(AttestationData)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Proof'
	if err = s.Proof.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedAggregatedAttestation object
func (s *SignedAggregatedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
