// Code generated by fastssz. DO NOT EDIT.
// Hash: 9fc6c6dea2131d3bc00342888a83608cd58920d9ea16a8cf71ab5dc1d452cd51
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the State object
func (s *State) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the State object to a target array
func (s *State) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(232)

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if dst, err = s.Config.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if dst, err = s.LatestBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if dst, err = s.LatestJustified.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if dst, err = s.LatestFinalized.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (5) 'HistoricalBlockHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.HistoricalBlockHashes) * 32

	// Offset (6) 'JustifiedSlots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustifiedSlots)

	// Offset (7) 'JustificationsRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustificationsRoots) * 32

	// Offset (8) 'JustificationsValidators'
	dst = ssz.WriteOffset(dst, offset)

	// Field (5) 'HistoricalBlockHashes'
	if size := len(s.HistoricalBlockHashes); size > 262144 {
		err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
		return
	}
	for ii := 0; ii < len(s.HistoricalBlockHashes); ii++ {
		dst = append(dst, s.HistoricalBlockHashes[ii][:]...)
	}

	// Field (6) 'JustifiedSlots'
	if size := len(s.JustifiedSlots); size > 262144 {
		err = ssz.ErrBytesLengthFn("State.JustifiedSlots", size, 262144)
		return
	}
	dst = append(dst, s.JustifiedSlots...)

	// Field (7) 'JustificationsRoots'
	if size := len(s.JustificationsRoots); size > 262144 {
		err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
		return
	}
	for ii := 0; ii < len(s.JustificationsRoots); ii++ {
		dst = append(dst, s.JustificationsRoots[ii][:]...)
	}

	// Field (8) 'JustificationsValidators'
	if size := len(s.JustificationsValidators); size > 1073741824 {
		err = ssz.ErrBytesLengthFn("State.JustificationsValidators", size, 1073741824)
		return
	}
	dst = append(dst, s.JustificationsValidators...)

	return
}

// UnmarshalSSZ ssz unmarshals the State object
func (s *State) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 232 {
		return ssz.ErrSize
	}

	tail := buf
	var o5, o6, o7, o8 uint64

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if err = s.Config.UnmarshalSSZ(buf[0:16]); err != nil {
		return err
	}

	// Field (1) 'Slot'
	s.Slot = ssz.UnmarshallUint64(buf[16:24])

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.UnmarshalSSZ(buf[24:136]); err != nil {
		return err
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.UnmarshalSSZ(buf[136:176]); err != nil {
		return err
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.UnmarshalSSZ(buf[176:216]); err != nil {
		return err
	}

	// Offset (5) 'HistoricalBlockHashes'
	if o5 = ssz.ReadOffset(buf[216:220]); o5 > size {
		return ssz.ErrOffset
	}

	if o5 != 232 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (6) 'JustifiedSlots'
	if o6 = ssz.ReadOffset(buf[220:224]); o6 > size || o5 > o6 {
		return ssz.ErrOffset
	}

	// Offset (7) 'JustificationsRoots'
	if o7 = ssz.ReadOffset(buf[224:228]); o7 > size || o6 > o7 {
		return ssz.ErrOffset
	}

	// Offset (8) 'JustificationsValidators'
	if o8 = ssz.ReadOffset(buf[228:232]); o8 > size || o7 > o8 {
		return ssz.ErrOffset
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		buf = tail[o5:o6]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.HistoricalBlockHashes = make([][32]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(s.HistoricalBlockHashes[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (6) 'JustifiedSlots'
	{
		buf = tail[o6:o7]
		if err = ssz.ValidateBitlist(buf, 262144); err != nil {
			return err
		}
		if cap(s.JustifiedSlots) == 0 {
			s.JustifiedSlots = make([]byte, 0, len(buf))
		}
		s.JustifiedSlots = append(s.JustifiedSlots, buf...)
	}

	// Field (7) 'JustificationsRoots'
	{
		buf = tail[o7:o8]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.JustificationsRoots = make([][32]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(s.JustificationsRoots[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (8) 'JustificationsValidators'
	{
		buf = tail[o8:]
		if err = ssz.ValidateBitlist(buf, 1073741824); err != nil {
			return err
		}
		if cap(s.JustificationsValidators) == 0 {
			s.JustificationsValidators = make([]byte, 0, len(buf))
		}
		s.JustificationsValidators = append(s.JustificationsValidators, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the State object
func (s *State) SizeSSZ() (size int) {
	size = 232

	// Field (5) 'HistoricalBlockHashes'
	size += len(s.HistoricalBlockHashes) * 32

	// Field (6) 'JustifiedSlots'
	size += len(s.JustifiedSlots)

	// Field (7) 'JustificationsRoots'
	size += len(s.JustificationsRoots) * 32

	// Field (8) 'JustificationsValidators'
	size += len(s.JustificationsValidators)

	return
}

// HashTreeRoot ssz hashes the State object
func (s *State) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the State object with a hasher
func (s *State) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if err = s.Config.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Slot'
	hh.PutUint64(s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		if size := len(s.HistoricalBlockHashes); size > 262144 {
			err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.HistoricalBlockHashes {
			hh.Append(i[:])
		}
		numItems := uint64(len(s.HistoricalBlockHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (6) 'JustifiedSlots'
	if len(s.JustifiedSlots) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustifiedSlots, 262144)

	// Field (7) 'JustificationsRoots'
	{
		if size := len(s.JustificationsRoots); size > 262144 {
			err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.JustificationsRoots {
			hh.Append(i[:])
		}
		numItems := uint64(len(s.JustificationsRoots))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (8) 'JustificationsValidators'
	if len(s.JustificationsValidators) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustificationsValidators, 1073741824)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the State object
func (s *State) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
