// Code generated by fastssz. DO NOT EDIT.
// Hash: 9fc6c6dea2131d3bc00342888a83608cd58920d9ea16a8cf71ab5dc1d452cd51
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Vote object
func (v *Vote) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the Vote object to a target array
func (v *Vote) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorID'
	dst = ssz.MarshalUint64(dst, v.ValidatorID)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, v.Slot)

	// Field (2) 'Head'
	if v.Head == nil {
		v.Head = new(Checkpoint)
	}
	if dst, err = v.Head.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Target'
	if v.Target == nil {
		v.Target = new(Checkpoint)
	}
	if dst, err = v.Target.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'Source'
	if v.Source == nil {
		v.Source = new(Checkpoint)
	}
	if dst, err = v.Source.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Vote object
func (v *Vote) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 136 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorID'
	v.ValidatorID = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Slot'
	v.Slot = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'Head'
	if v.Head == nil {
		v.Head = new(Checkpoint)
	}
	if err = v.Head.UnmarshalSSZ(buf[16:56]); err != nil {
		return err
	}

	// Field (3) 'Target'
	if v.Target == nil {
		v.Target = new(Checkpoint)
	}
	if err = v.Target.UnmarshalSSZ(buf[56:96]); err != nil {
		return err
	}

	// Field (4) 'Source'
	if v.Source == nil {
		v.Source = new(Checkpoint)
	}
	if err = v.Source.UnmarshalSSZ(buf[96:136]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Vote object
func (v *Vote) SizeSSZ() (size int) {
	size = 136
	return
}

// HashTreeRoot ssz hashes the Vote object
func (v *Vote) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the Vote object with a hasher
func (v *Vote) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorID'
	hh.PutUint64(v.ValidatorID)

	// Field (1) 'Slot'
	hh.PutUint64(v.Slot)

	// Field (2) 'Head'
	if v.Head == nil {
		v.Head = new(Checkpoint)
	}
	if err = v.Head.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Target'
	if v.Target == nil {
		v.Target = new(Checkpoint)
	}
	if err = v.Target.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'Source'
	if v.Source == nil {
		v.Source = new(Checkpoint)
	}
	if err = v.Source.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Vote object
func (v *Vote) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}

// MarshalSSZ ssz marshals the SignedVote object
func (s *SignedVote) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedVote object to a target array
func (s *SignedVote) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(Vote)
	}
	if dst, err = s.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedVote object
func (s *SignedVote) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 168 {
		return ssz.ErrSize
	}

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(Vote)
	}
	if err = s.Data.UnmarshalSSZ(buf[0:136]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[136:168])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedVote object
func (s *SignedVote) SizeSSZ() (size int) {
	size = 168
	return
}

// HashTreeRoot ssz hashes the SignedVote object
func (s *SignedVote) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedVote object with a hasher
func (s *SignedVote) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	if s.Data == nil {
		s.Data = new(Vote)
	}
	if err = s.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedVote object
func (s *SignedVote) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
