{
 "title": "Lean Ethereum Clients Dashboard",
 "tags": [
  "interop",
  "Client"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "ethlambda,gean,grandine,lantern,lighthouse,qlean,ream,zeam"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (lean_node_start_time_seconds{job=~\"$job\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of attestation committees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "max(lean_attestation_committee_count{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lean_is_aggregator{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators  per node",
   "type": "piechart",
   "description": "Number of validators attached to each node",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (lean_validators_count)", "legendFormat": "Total" },
    {
     "expr": "sum by (job) (lean_validators_count{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "lean_node_info{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest finalized slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(lean_latest_finalized_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "max(lean_latest_justified_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "max(lean_head_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Latest finalized slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job)(lean_latest_finalized_slot{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": " sum by (job) (lean_latest_justified_slot{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": " sum by (job) (lean_head_slot{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": " sum by (job) (lean_current_slot{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "changes(lean_node_start_time_seconds{job=~\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": " sum by (job) (lean_connected_peers{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Attestation committee subnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "sum by (job) (lean_attestation_committee_subnet{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalization/Justification Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Head - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{job=~\"$job\"}[5m]) - avg_over_time(lean_latest_finalized_slot{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Justified delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(lean_head_slot{job=~\"$job\"}[5m]) - avg_over_time(lean_latest_justified_slot{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Justified - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(lean_latest_justified_slot{job=~\"$job\"}[5m]) - avg_over_time(lean_latest_finalized_slot{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Connected peers per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": " sum by (job) (lean_connected_peers{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connected peers per node (detailed)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": " sum by (job, client) (lean_connected_peers{job=~\"$job\", client!=\"\"})",
     "legendFormat": "{{job}} - {{client}}"
    }
   ]
  },
  {
   "title": "Peer connection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (job) (\n    increase(lean_peer_connection_events_total{job=~\"$job\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peer disconnection events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (job) (\n    increase(lean_peer_disconnection_events_total{job=~\"$job\"}[$__rate_interval])\n  )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "PQ Signatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Total number of attestation signatures",
   "type": "timeseries",
   "description": "Total number of individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_attestation_signatures_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid attestation signatures",
   "type": "timeseries",
   "description": "Total number of valid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_attestation_signatures_valid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid attestation signatures",
   "type": "timeseries",
   "description": "Total number of invalid individual attestation signatures",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_attestation_signatures_invalid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to sign an attestation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_attestation_signing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an attestation signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_attestation_verification_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_aggregated_signatures_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of attestations included into aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_attestations_in_aggregated_signatures_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of valid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_aggregated_signatures_valid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of invalid aggregated signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_pq_sig_aggregated_signatures_invalid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to build an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_aggregated_signatures_building_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify an aggregated signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_sig_aggregated_signatures_verification_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Fork-Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_fork_choice_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to aggregate committee signatures",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_committee_signatures_aggregation_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of fork choice reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(lean_fork_choice_reorgs_total{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Depth of fork choice reorgs (in blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(lean_fork_choice_reorg_depth_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of gossip signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": " sum by (job) (lean_gossip_signatures{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of new aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "targets": [
    {
     "expr": " sum by (job) (lean_latest_new_aggregated_payloads{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of known aggregated payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "targets": [
    {
     "expr": " sum by (job) (lean_latest_known_aggregated_payloads{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_attestations_valid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Invalid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_attestations_invalid_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Safe target slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": " sum by (job) (lean_safe_target_slot{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Processed attestations",
   "type": "timeseries",
   "description": "Total number of attestations processed in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_state_transition_attestations_processed_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Attestations processing time",
   "type": "timeseries",
   "description": "Time taken to process attestations in state transition function",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_attestations_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (\n    increase(lean_attestations_valid_total{job=~\"$job\"}[$__rate_interval])\n  )[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "State Transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "State transition time",
   "type": "timeseries",
   "description": "Time taken to process state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed slots",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_state_transition_slots_processed_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slots processing time",
   "type": "timeseries",
   "description": "Time taken to process slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_slots_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Finalizations total",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_finalizations_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 } }
 ]
}