/*
 * leanmultisig_ffi.h - Auto-generated C header for the leanmultisig FFI library.
 *
 * DO NOT EDIT MANUALLY. This file is generated by cbindgen from src/lib.rs.
 * Run `cargo build` to regenerate.
 */

#ifndef LEANMULTISIG_FFI_H
#define LEANMULTISIG_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
/* Message hash length expected by aggregate/verify (32-byte attestation root). */
#define LEANMULTISIG_MESSAGE_HASH_LENGTH 32

typedef enum LeanmultisigResult {
  LEANMULTISIG_RESULT_OK = 0,
  LEANMULTISIG_RESULT_NULL_POINTER = 1,
  LEANMULTISIG_RESULT_INVALID_LENGTH = 2,
  LEANMULTISIG_RESULT_LENGTH_MISMATCH = 3,
  LEANMULTISIG_RESULT_DESERIALIZATION_FAILED = 4,
  LEANMULTISIG_RESULT_AGGREGATION_FAILED = 5,
  LEANMULTISIG_RESULT_VERIFICATION_FAILED = 6,
} LeanmultisigResult;

typedef struct LeanmultisigBytes {
  const uint8_t *data;
  size_t len;
} LeanmultisigBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initialize prover-side aggregation setup. Idempotent.
void leanmultisig_setup_prover(void);

// Initialize verifier-side setup. Idempotent.
void leanmultisig_setup_verifier(void);

// Aggregate XMSS signatures into a devnet-2 leanMultisig proof.
//
// The caller owns the returned buffer and must free it via `leanmultisig_bytes_free`.
enum LeanmultisigResult leanmultisig_aggregate(const struct LeanmultisigBytes *pubkeys,
                                               size_t num_pubkeys,
                                               const struct LeanmultisigBytes *signatures,
                                               size_t num_signatures,
                                               const uint8_t *message_hash_ptr,
                                               size_t message_hash_len,
                                               uint32_t epoch,
                                               uint8_t **out_data,
                                               size_t *out_len);

// Verify a devnet-2 leanMultisig proof.
enum LeanmultisigResult leanmultisig_verify_aggregated(const struct LeanmultisigBytes *pubkeys,
                                                       size_t num_pubkeys,
                                                       const uint8_t *message_hash_ptr,
                                                       size_t message_hash_len,
                                                       const uint8_t *proof_data,
                                                       size_t proof_len,
                                                       uint32_t epoch);

// Free a buffer allocated by `leanmultisig_aggregate`.
void leanmultisig_bytes_free(uint8_t *data, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LEANMULTISIG_FFI_H */
